## What are Tensors?

In simple terms, tensors are the fundamental data structures used in deep learning. WE can think of them as multi-dimensional arrays or a generalization of vectors and matrices:

- A 0D tensor is a single number (scalar)
- 1D tensor is a list of numbers (vectors)
- A 2D tensor is a table of numbers (matrix)

# Topics covered

- Introduction to Tensors
- Getting information from Tensors
- Manipulating Tensors
- Tensors and Numpy
- Using GPUs


In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [2]:
# Creating a tensor with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions in a tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([2, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[2, 7], [8, 9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 7],
       [8, 9]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix with different dtype
another_matrix = tf.constant([[1.1, 0.2],
[10.11, 9.11],
[7, 4.29]], dtype=tf.float16)

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1, 2, 3],
                    [3, 4, 5]],
                    [[6,7, 8],
                    [10, 11, 12]]])

tensor.ndim


3

In [11]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [10, 11, 12]]], dtype=int32)>

### Create tensors with tf.variable()

In [12]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

In [13]:
# assign a new value
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = tf.random.uniform(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.64654624, 0.9347383 ],
       [0.5127678 , 0.16937864],
       [0.5227008 , 0.58687484]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = tf.random.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.05139995, 0.1602608 ],
       [0.68792856, 0.07285655],
       [0.7273631 , 0.53601   ]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[2,3],
[4,5],
[6, 7]])

In [ ]:
not_shuffled.ndim

2

In [ ]:
shuffled_tensor = tf.random.shuffle(not_shuffled, seed=23)

In [ ]:
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [2, 3],
       [4, 5]], dtype=int32)>

Other way to make tensors

In [ ]:
one_tensors = tf.ones(shape=(2, 4), dtype=tf.int32)
one_tensors

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [ ]:
one_tensors

<tf.Tensor: shape=(2,), dtype=uint8, numpy=array([1, 1], dtype=uint8)>

In [ ]:
tf.zeros(shape=(2, 7))

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros(2, 6)

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([0, 0], dtype=int8)>

In [ ]:
# Convert numpy arrays to tf arrays
import numpy as np 

arr = np.arange(1, 25, dtype=np.int32)
tfarr = tf.constant(arr)
tfarr

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
arr_b = tf.constant(arr, shape=(3, 2, 4))
arr_b

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [15]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
# First two elements of the dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
# Get each element from each index except the final one
rank_4_tensor[:-1, :-1, :-1, :-1]

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

## Manipulating Tensors

**Basic Operations** 

`+` `-` `x` `/`

In [23]:
# Addidng Values
tensor = tf.constant([[2, 6], [2, 5]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 6],
       [2, 5]], dtype=int32)>

In [26]:
tensor_new = tensor + 10
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 16],
       [12, 15]], dtype=int32)>

In [28]:
# Multiplication
tensor_mult = tensor * 10
tensor_mult

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 60],
       [20, 50]], dtype=int32)>

In [29]:
# using the built-in function
tensor_new = tf.multiply(tensor, 100)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 600],
       [200, 500]], dtype=int32)>

In [30]:
tensor_new = tf.divide(tensor, 100)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.02, 0.06],
       [0.02, 0.05]])>

**Matrix Multiplication**

**read** = https://www.mathsisfun.com/algebra/matrix-multiplying.html

**Try MM** = http://matrixmultiplication.xyz/


In [33]:
tensor_1 = tf.constant([[[1, 2, 1], [0, 1, 0], [2, 3, 4]]])
tensor_1

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 1],
        [0, 1, 0],
        [2, 3, 4]]], dtype=int32)>

In [34]:
tensor_2 = tf.constant([[2, 5], [6, 7], [1, 8]])
tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [35]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[15, 27],
        [ 6,  7],
        [26, 63]]], dtype=int32)>

In [37]:
# built-in python mehtod for matrix multiplication
tensor_1 @ tensor_2

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[15, 27],
        [ 6,  7],
        [26, 63]]], dtype=int32)>

**For Matrix multiplication, the inner dimensions should match, for eg, we can only multiply matrices of dimension 5 x 4 and 4 x 6 as 4=4 here, and the new matrix thus produced will be 5 x 6**

In [38]:
# Transpose
transposed_tensor = tf.transpose(tensor_1)
transposed_tensor

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [0],
        [2]],

       [[2],
        [1],
        [3]],

       [[1],
        [0],
        [4]]], dtype=int32)>

In [39]:
tensor_1

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 1],
        [0, 1, 0],
        [2, 3, 4]]], dtype=int32)>